import os.path
import lxml.etree


def convert_command_element(el):
    """Convert an lxml element of a command to a tuple:

    (command, <arg1>, <arg2>, ...)

    """
    command = el.get('name')
    raw_args = el.tail.replace(command, '').replace('(', '').replace(')', '')
    if raw_args.strip():
        args = tuple(x.strip() for x in raw_args.split(','))
    else:
        # Prevent argument form being an empty string:
        args = ()
    return (command, ) + args


def extract(path):
    """Extract commands and arguments from reference.html into a list."""
    ref = os.path.join(path, 'reference.html')
    parser = lxml.etree.XMLParser(remove_blank_text=True, recover=True)
    tree = lxml.etree.parse(ref, parser=parser)
    command_elements = tree.xpath('//strong/a')
    commands = [convert_command_element(e) for e in command_elements]
    print commands
    # TODO: added autogenerated commands
    return commands